title: Kapil Kataria | Drupal Developer
description: Hey there! you are visiting the portfolio of Kapil Kataria, that's me! I am a Drupal Developer Focused on developing and maintaining web applications for clients using Agile methodologies. In this role, I understand client's bussiness needs and develop a software solution with proper standards and necessary validations. I have the capabilities to learn new things and the ability to adapt the changes as per environment.

permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

theme: jekyll-theme-primer
